server {
    listen 8080;

    location /service-a/ {
        proxy_pass http://service-a:3000/service-a/;
        # rewrite ^/service-a(/.*)$ $1 break;
    }

    location /service-b/ {
        proxy_pass http://service-b:4000/service-b/;
    }

    location /service-c/ {
        proxy_pass http://service-c:5000/service-c/;
    }
}
